<?php

if(function_exists("register_field_group")) {
	register_field_group(array (
		'id' => 'acf_lightbox-options',
		'title' => 'Lightbox Options',
		'fields' => array (
			array (
				'key' => 'field_555ca8052ed11',
				'label' => 'Display Lightbox On',
				'name' => 'coverlay_visibility',
				'type' => 'select',
				'choices' => array (
					'home' => 'Homepage',
					'all' => 'All Pages',
					'none' => 'Nowhere',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_555ca85e2ed12',
				'label' => 'Once Seen',
				'name' => 'coverlay_suppress',
				'type' => 'select',
				'instructions' => 'What should happen once a user has seen the lightbox once?',
				'choices' => array (
					'never' => 'Keep showing it',
					'session' => 'Don\'t show again this browser session',
					'wait-7' => 'Wait a week before showing again',
					'wait-30' => 'Wait 30 days before showing again',
					'wait-90' => 'Wait 90 days before showing again',
					'always' => 'Never show again',
				),
				'default_value' => 'wait-7',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_555ca9682ed13',
				'label' => 'Trigger',
				'name' => 'coverlay_trigger',
				'type' => 'select',
				'instructions' => 'When does the lightbox appear?',
				'choices' => array (
					'immediate' => 'Immediately on page load',
					'delay' => 'N seconds after load (specify)',
					'scroll' => 'After page is scrolled N pixels (specify)',
					'scroll-half' => 'After page is scrolled halfway',
					'minutes' => 'After N minutes spent on site this visit (specify)',
					'pages' => 'Once N pages have been visited in last 90 days (specify)',
				),
				'default_value' => 'immediate',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_555caca92ed16',
				'label' => 'Trigger amount',
				'name' => 'coverlay_trigger_amount',
				'type' => 'number',
				'instructions' => 'Specify the precise quantity/time/amount/number for the above',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_555ca9682ed13',
							'operator' => '!=',
							'value' => 'immediate',
						),
						array (
							'field' => 'field_555ca9682ed13',
							'operator' => '!=',
							'value' => 'scroll-half',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => 1,
			),
			array (
				'key' => 'field_555cabc52ed14',
				'label' => 'Content',
				'name' => 'coverlay_content',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_555cac132ed15',
				'label' => 'Overlay Identifier',
				'name' => 'overlay_id',
				'prefix' => '',
				'type' => 'text',
				'instructions' => 'Enter a name or number to uniquely identify the current overlay. Change this when revising the overlay content so as to reset users\' cookies.',
				'required' => 1,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => 64,
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5564c912cdd8d',
				'label' => 'Max Width',
				'name' => 'coverlay_max_width',
				'prefix' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'px',
				'min' => '',
				'max' => '',
				'step' => 1,
				'readonly' => 0,
				'disabled' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'conditional-overlay',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
